name: Sync to S3

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Project Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run generate
    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
  deploy:
    name: Project Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download dist folder
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Print contents
      shell: bash
      run: |
        value=`ls -R`
        echo The contents are $value
    # Set the credentials from repository settings/secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    # Copy the files from build folder to the S3 bucket
    - name: Deploy to S3
      run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete --metadata '{"Cache-Control":"max-age=31536000"}'
      working-directory: dist
    - name: Invalidate CDN
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CDN_ID }} --paths "/*"
